(eval-when-compile    (require'color-theme))
(defun color-theme-euphoria ()
  "Color theme by Yang Guang, created 2011-12-25."
  (interactive)
  (color-theme-install
   '(color-theme-euphoria
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "yellow")
      (foreground-color . "#00ff00")
      (mouse-color . "yellow"))
     ((cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "red")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (ns-use-system-highlight-color . t)
      (php-default-face . default)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (viper-replace-overlay-cursor-color . "red4")
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Monaco"))))
     (aquamacs-variable-width ((t (:stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 120 :width normal :family "Lucida Grande"))))
     (autoface-default ((t (:family "Monaco" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#00ff00" :background "black" :stipple nil :height 120))))
     (blank-newline ((t (:foreground "lightgrey" :weight normal))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (completion-list-mode-default ((t (:stipple nil :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "apple" :family "Monaco" :height 120))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "Monaco" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#00ff00" :background "black" :stipple nil :height 120))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "yellow"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "light blue"))))
     (custom-group-tag ((t (:bold t :family "helv" :foreground "light blue" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "helv" :foreground "pink" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "cyan1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "cyan1" :height 0.8))))
     (echo-area ((t (:stipple nil :strike-through nil :underline nil :slant normal :weight normal :width normal :family "Lucida Grande"))))
     (emacs-lisp-mode-default ((t (:stipple nil :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "apple" :family "Monaco" :height 120))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "courier"))))
     (font-lock-builtin-face ((t (:foreground "magenta"))))
     (font-lock-comment-delimiter-face ((t (:foreground "deeppink"))))
     (font-lock-comment-face ((t (:foreground "deeppink"))))
     (font-lock-constant-face ((t (:foreground "blue"))))
     (font-lock-doc-face ((t (:foreground "cyan"))))
     (font-lock-doc-string-face ((t (:foreground "cyan"))))
     (font-lock-function-name-face ((t (:foreground "purple"))))
     (font-lock-keyword-face ((t (:foreground "red"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "blue1"))))
     (font-lock-reference-face ((t (nil))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "cyan"))))
     (font-lock-type-face ((t (:foreground "yellow"))))
     (font-lock-variable-name-face ((t (:foreground "violet"))))
     (font-lock-warning-face ((t (:bold t :foreground "red" :weight bold))))
     (fringe ((t (:background "gray16" :foreground "#00ff00"))))
     (fundamental-mode-default ((t (:stipple nil :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "apple" :family "Monaco" :height 120))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (help-mode-default ((t (:stipple nil :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "apple" :family "Monaco" :height 120))))
     (highlight ((t (:background "darkolivegreen"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (italic ((t (:italic t :slant italic))))
     (latex-mode-default ((t (:stipple nil :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :foundry "apple" :stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 130 :width normal :family "Lucida Grande"))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (linum ((t (:foreground "grey70" :height 110))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:background "gray16" :foreground "green"))))
     (minibuffer ((t (:family "Lucida Grande" :width normal :weight normal :slant normal :underline nil :strike-through nil :stipple nil))))
     (minibuffer-prompt ((t (:stipple nil :strike-through nil :underline nil :slant normal :weight normal :width normal :family "Lucida Grande" :foreground "cyan"))))
     (mode-line ((t (:family "Lucida Grande" :underline nil :strike-through nil :stipple nil :background "gray16" :foreground "#00ff00" :box (:line-width -1 :style released-button) :strike-through nil :underline nil :slant normal :weight normal :width normal :height 120))))
     (mode-line-buffer-id ((t (:bold t :background "gray16" :foreground "#00ff00" :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-flags ((t (:family "Monaco"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:family "Lucida Grande" :underline nil :strike-through nil :stipple nil :background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :strike-through nil :underline nil :slant normal :weight normal :width normal :height 120))))
     (modeline-mousable ((t (:background "gray16" :foreground "#00ff00"))))
     (modeline-mousable-minor-mode ((t (:background "gray16" :foreground "#00ff00"))))
     (mouse ((t (:background "yellow"))))
     (next-error ((t (:foreground "white" :background "steelblue"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (notify-user-of-mode ((t (:foreground "cyan"))))
     (ns-working-text-face ((t (:underline t))))
     (org-mode-default ((t (:stipple nil :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :foundry "apple" :stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 120 :width normal :family "Monaco"))))
     (primary-selection ((t (:background "#00ff00" :foreground "black"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (region ((t (:background "steelblue" :foreground "white"))))
     (scroll-bar ((t (:background "gray16" :foreground "#00ff00"))))
     (secondary-selection ((t (:background "#00ff00" :foreground "black"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:bold t :foreground "red" :weight bold))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "#00ff00"))))
     (speedbar-directory-face ((t (:foreground "#00ff00"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "#00ff00" :foreground "purple"))))
     (speedbar-selected-face ((t (:foreground "deeppink" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (text-mode-default ((t (:stipple nil :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :foundry "apple" :stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 130 :width normal :family "Lucida Grande"))))
     (tool-bar ((t (:background "gray16" :foreground "green" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "gray16" :foreground "#00ff00"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (which-func ((t (:foreground "Blue1"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (zmacs-region ((t (:background "steelblue" :foreground "white")))))))
(add-to-list 'color-themes '(color-theme-euphoria  "color-theme-euphoria" "YOUR NAME"))
